name: CI/CD Pipeline

on:
 push:
   branches:
     - main


jobs:
 build-and-deploy:
   runs-on: ubuntu-latest


   steps:
     - name: Checkout code
       uses: actions/checkout@v3


     - name: Build Docker image
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .


     - name: Log in to Docker Hub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


     - name: Push Docker image
       run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

     - name: Deploy to Docker Swarm
       uses: appleboy/ssh-action@v1.0.3
       continue-on-error: true
       with:
         host: ${{ secrets.SWARM_HOST }}
         username: user
         key: ${{ secrets.SWARM_SSH_KEY }}
         script: |
           echo "Deploying image: ${{ secrets.DOCKER_USERNAME }}/my-app:latest"
           docker service update --image ${{ secrets.DOCKER_USERNAME }}/my-app:latest my-app_app
     